package com.tastedaily.core.seed

import com.tastedaily.core.model.Article
import com.tastedaily.core.model.ArticleSection
import com.tastedaily.core.model.CookingStep
import com.tastedaily.core.model.Difficulty
import com.tastedaily.core.model.Dish
import com.tastedaily.core.model.Ingredient
import com.tastedaily.core.model.VideoAsset
import java.net.URLEncoder

/**
 * Built-in recipe catalog used as the demo data source. In production this would come from a
 * backend that publishes a new dish every day; see [com.tastedaily.core.domain.DailyDishSelector].
 */
object DishCatalog {

    /** Sample MP4 used for cooking-step / preview videos in the demo build. */
    private const val SAMPLE_VIDEO =
        "https://storage.googleapis.com/exoplayer-test-media-0/BigBuckBunny.mp4"

    private fun foodImage(prompt: String): String =
        "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image" +
            "?prompt=" + URLEncoder.encode("$prompt，中式美食摄影，俯视，暖色调，专业摆盘", "UTF-8") +
            "&image_size=landscape_4_3"

    val all: List<Dish> = listOf(
        Dish(
            id = "kung_pao_chicken",
            name = "宫保鸡丁",
            tagline = "鲜辣微甜，川味经典下饭神菜",
            cuisine = "川菜",
            coverImageUrl = foodImage("宫保鸡丁"),
            difficulty = Difficulty.MEDIUM,
            durationMinutes = 25,
            calories = 480,
            ingredients = listOf(
                Ingredient("鸡胸肉", "300 克"),
                Ingredient("熟花生米", "80 克"),
                Ingredient("干辣椒", "10 克"),
                Ingredient("花椒", "3 克"),
                Ingredient("葱白", "30 克"),
                Ingredient("生抽", "2 勺"),
                Ingredient("香醋", "1 勺"),
                Ingredient("白糖", "1 勺"),
                Ingredient("淀粉", "1 勺"),
            ),
            description = "宫保鸡丁是一道享誉海内外的川菜，鸡肉滑嫩、花生酥脆、糊辣荔枝味浓郁。" +
                "讲究旺火快炒、三次下料，做到肉嫩、葱香、花生脆。",
            article = Article(
                title = "宫保鸡丁的前世今生",
                author = "味道日历编辑部",
                sections = listOf(
                    ArticleSection(
                        "起源",
                        "相传清代四川总督丁宝桢爱吃花生与鸡丁，家厨将两者结合并佐以糊辣荔枝味，" +
                            "因丁宝桢被封“太子少保”（宫保），这道菜便得名“宫保鸡丁”。",
                    ),
                    ArticleSection(
                        "灵魂在于“荔枝味型”",
                        "宫保味属于川菜复合味型之一，以生抽、香醋、白糖调成微酸回甜的底味，" +
                            "再以干辣椒、花椒炝锅带出糊辣香，最后勾薄芡让味道裹住每一粒鸡丁。",
                    ),
                    ArticleSection(
                        "三个让花生不软的小窍门",
                        "1）花生临出锅再下；2）鸡丁要浆透锁水；3）兑汁一次倒入快速翻匀即出锅。",
                    ),
                ),
            ),
            videos = listOf(
                VideoAsset("v1", "宫保鸡丁完整教学", SAMPLE_VIDEO, foodImage("宫保鸡丁成品"), 596),
                VideoAsset("v2", "怎样切出滑嫩鸡丁", SAMPLE_VIDEO, foodImage("切鸡丁特写"), 180),
            ),
            steps = listOf(
                CookingStep(1, "浆制鸡丁", "鸡胸肉切 1.5cm 方丁，加盐、生抽、料酒、蛋清、淀粉抓匀，封油静置 10 分钟。", 120, foodImage("浆制鸡丁"), null),
                CookingStep(2, "兑碗芡", "生抽、香醋、白糖、盐、淀粉、少许高汤调成荔枝味碗芡备用。", 60, foodImage("碗芡调料"), null),
                CookingStep(3, "炝锅出味", "冷油下花椒小火炸香，再下干辣椒段至棕红，糊辣香气溢出。", 90, foodImage("炝锅辣椒"), SAMPLE_VIDEO),
                CookingStep(4, "滑炒鸡丁", "鸡丁下锅迅速划散，至变色发白、表面微金黄。", 150, foodImage("滑炒鸡丁"), null),
                CookingStep(5, "烹汁合炒", "倒入碗芡快速翻炒，让酱汁裹匀鸡丁，下葱白段翻匀。", 90, foodImage("烹汁翻炒"), null),
                CookingStep(6, "出锅点花生", "关火，撒入熟花生米略翻即可出锅装盘。", 60, foodImage("宫保鸡丁成品"), null),
            ),
        ),
        Dish(
            id = "tomato_egg",
            name = "番茄炒蛋",
            tagline = "国民家常菜，三分钟出锅",
            cuisine = "家常菜",
            coverImageUrl = foodImage("番茄炒蛋"),
            difficulty = Difficulty.EASY,
            durationMinutes = 10,
            calories = 280,
            ingredients = listOf(
                Ingredient("鸡蛋", "4 个"),
                Ingredient("番茄", "2 个（约 300 克）"),
                Ingredient("葱花", "20 克"),
                Ingredient("盐", "适量"),
                Ingredient("白糖", "1 小勺"),
                Ingredient("食用油", "2 勺"),
            ),
            description = "番茄炒蛋是中国家庭餐桌上出镜率最高的菜之一，番茄出汁、鸡蛋蓬松，酸甜下饭。",
            article = Article(
                title = "让番茄炒蛋更好吃的细节",
                author = "味道日历编辑部",
                sections = listOf(
                    ArticleSection("先炒蛋还是先炒番茄", "先炒蛋。蛋液中火下锅，刚凝固便盛出，避免回锅后变老。"),
                    ArticleSection("番茄要出汁", "番茄下锅加少许盐和糖小火煸炒至出红油汤汁，再回锅鸡蛋吸味。"),
                ),
            ),
            videos = listOf(
                VideoAsset("v1", "番茄炒蛋零失败教学", SAMPLE_VIDEO, foodImage("番茄炒蛋"), 240),
            ),
            steps = listOf(
                CookingStep(1, "打蛋液", "鸡蛋打散，加少许盐和一勺清水打至起泡，炒出来更蓬松。", 60, foodImage("打蛋液"), null),
                CookingStep(2, "炒蛋盛出", "热锅冷油，蛋液下锅迅速推炒至刚凝固，盛出备用。", 90, foodImage("炒鸡蛋"), null),
                CookingStep(3, "炒番茄出汁", "番茄块下锅，加少许盐和糖，小火煸炒至出红油汤汁。", 150, foodImage("炒番茄出汁"), SAMPLE_VIDEO),
                CookingStep(4, "合炒出锅", "鸡蛋回锅翻匀，撒葱花出锅。", 60, foodImage("番茄炒蛋"), null),
            ),
        ),
        Dish(
            id = "red_braised_pork",
            name = "红烧肉",
            tagline = "肥而不腻，入口即化的本帮味道",
            cuisine = "本帮菜",
            coverImageUrl = foodImage("红烧肉"),
            difficulty = Difficulty.HARD,
            durationMinutes = 90,
            calories = 620,
            ingredients = listOf(
                Ingredient("带皮五花肉", "500 克"),
                Ingredient("冰糖", "40 克"),
                Ingredient("生抽", "3 勺"),
                Ingredient("老抽", "1 勺"),
                Ingredient("料酒", "2 勺"),
                Ingredient("姜片", "20 克"),
                Ingredient("八角", "2 颗"),
                Ingredient("热水", "适量"),
            ),
            description = "红烧肉讲究糖色红亮、肉酥汁浓，肥肉入口即化，瘦肉不柴不塞牙。",
            article = Article(
                title = "一锅好红烧肉的三个关键",
                author = "味道日历编辑部",
                sections = listOf(
                    ArticleSection("炒糖色", "冰糖小火慢熬至琥珀色起密集小泡，是红亮不苦的关键。"),
                    ArticleSection("加热水", "炖肉一定要加热水，冷水会让蛋白质收缩变柴。"),
                    ArticleSection("收汁", "最后大火收汁不断翻动，让每块肉都裹上浓稠酱汁。"),
                ),
            ),
            videos = listOf(
                VideoAsset("v1", "红烧肉慢炖全过程", SAMPLE_VIDEO, foodImage("红烧肉"), 900),
                VideoAsset("v2", "怎样炒出完美糖色", SAMPLE_VIDEO, foodImage("炒糖色"), 120),
            ),
            steps = listOf(
                CookingStep(1, "焯水切块", "五花肉冷水下锅，加料酒姜片煮开撇沫，捞出切 3cm 方块。", 300, foodImage("焯水"), null),
                CookingStep(2, "炒糖色", "少许油下冰糖小火熬至琥珀色起小泡。", 180, foodImage("炒糖色"), SAMPLE_VIDEO),
                CookingStep(3, "上色", "肉块下锅迅速翻炒，让每块肉裹上糖色。", 120, foodImage("红烧肉上色"), null),
                CookingStep(4, "调味炖煮", "加生抽、老抽、料酒、八角、姜片，倒入没过肉的热水，小火炖 50 分钟。", 3000, foodImage("炖煮红烧肉"), null),
                CookingStep(5, "收汁装盘", "大火收汁至浓稠，翻匀装盘。", 300, foodImage("红烧肉"), null),
            ),
        ),
        Dish(
            id = "mapo_tofu",
            name = "麻婆豆腐",
            tagline = "麻、辣、烫、香、酥、嫩、鲜",
            cuisine = "川菜",
            coverImageUrl = foodImage("麻婆豆腐"),
            difficulty = Difficulty.MEDIUM,
            durationMinutes = 20,
            calories = 360,
            ingredients = listOf(
                Ingredient("嫩豆腐", "1 盒（约 400 克）"),
                Ingredient("牛肉末", "100 克"),
                Ingredient("郫县豆瓣酱", "1.5 勺"),
                Ingredient("豆豉", "1 勺"),
                Ingredient("花椒粉", "适量"),
                Ingredient("蒜苗", "30 克"),
                Ingredient("水淀粉", "适量"),
            ),
            description = "麻婆豆腐讲究“八字真言”：麻、辣、烫、香、酥、嫩、鲜、活，是川菜代表。",
            article = Article(
                title = "麻婆豆腐的“八字真言”",
                author = "味道日历编辑部",
                sections = listOf(
                    ArticleSection("麻辣之源", "花椒的“麻”与郫县豆瓣的“辣”共同构成麻婆豆腐的灵魂底味。"),
                    ArticleSection("豆腐不碎", "豆腐先焯水去豆腥并定型，下锅后轻推不铲，三次勾薄芡让味挂住。"),
                ),
            ),
            videos = listOf(
                VideoAsset("v1", "麻婆豆腐完整教学", SAMPLE_VIDEO, foodImage("麻婆豆腐"), 360),
            ),
            steps = listOf(
                CookingStep(1, "豆腐焯水", "豆腐切 2cm 方块，淡盐水焯 1 分钟捞出沥干。", 120, foodImage("豆腐焯水"), null),
                CookingStep(2, "炒牛肉末", "牛肉末小火煸至酥香出油。", 120, foodImage("炒牛肉末"), null),
                CookingStep(3, "炒豆瓣红油", "下豆瓣酱、豆豉剁碎炒出红油，加蒜末姜末。", 90, foodImage("炒豆瓣红油"), SAMPLE_VIDEO),
                CookingStep(4, "烧豆腐", "加高汤、豆腐，中火烧 3 分钟，分三次勾薄芡。", 240, foodImage("烧豆腐"), null),
                CookingStep(5, "出锅点花椒", "盛碗，撒花椒粉和蒜苗末。", 30, foodImage("麻婆豆腐"), null),
            ),
        ),
        Dish(
            id = "yu_xiang_pork",
            name = "鱼香肉丝",
            tagline = "吃鱼不见鱼，鱼香惹人馋",
            cuisine = "川菜",
            coverImageUrl = foodImage("鱼香肉丝"),
            difficulty = Difficulty.MEDIUM,
            durationMinutes = 20,
            calories = 380,
            ingredients = listOf(
                Ingredient("猪里脊", "250 克"),
                Ingredient("水发木耳", "60 克"),
                Ingredient("冬笋", "80 克"),
                Ingredient("泡红椒", "30 克"),
                Ingredient("葱姜蒜末", "共 30 克"),
                Ingredient("生抽", "2 勺"),
                Ingredient("香醋", "3 勺"),
                Ingredient("白糖", "2 勺"),
            ),
            description = "鱼香肉丝没有鱼，靠泡椒、糖醋调出“鱼香”复合味，是川菜名馔。",
            article = Article(
                title = "鱼香味是怎么来的",
                author = "味道日历编辑部",
                sections = listOf(
                    ArticleSection("没有鱼的鱼香", "泡椒茸与葱姜蒜爆出香气，配合糖醋比例（糖醋约 2:3），模拟出类似泡菜鱼的鲜香。"),
                    ArticleSection("丝要均匀", "里脊、木耳、冬笋都切细丝，成熟一致、口感统一。"),
                ),
            ),
            videos = listOf(
                VideoAsset("v1", "鱼香肉丝教学", SAMPLE_VIDEO, foodImage("鱼香肉丝"), 300),
            ),
            steps = listOf(
                CookingStep(1, "切丝浆肉", "里脊切细丝，加盐、料酒、水淀粉抓匀；冬笋、木耳切丝。", 180, foodImage("切丝"), null),
                CookingStep(2, "兑鱼香汁", "生抽、香醋、白糖、盐、水淀粉、高汤调成鱼香碗芡。", 60, foodImage("鱼香汁"), null),
                CookingStep(3, "炒泡椒", "热油下泡椒茸、姜蒜末炒红出香。", 90, foodImage("炒泡椒"), SAMPLE_VIDEO),
                CookingStep(4, "滑炒肉丝", "肉丝下锅划散变色。", 90, foodImage("滑炒肉丝"), null),
                CookingStep(5, "合炒烹汁", "下笋丝木耳丝翻炒，倒入鱼香汁翻匀出锅。", 90, foodImage("鱼香肉丝"), null),
            ),
        ),
        Dish(
            id = "scallion_noodles",
            name = "葱油拌面",
            tagline = "一把面条一勺葱油，简单到极致",
            cuisine = "沪式面点",
            coverImageUrl = foodImage("葱油拌面"),
            difficulty = Difficulty.EASY,
            durationMinutes = 30,
            calories = 410,
            ingredients = listOf(
                Ingredient("细面条", "200 克"),
                Ingredient("小葱", "150 克"),
                Ingredient("食用油", "100 毫升"),
                Ingredient("生抽", "3 勺"),
                Ingredient("老抽", "1 勺"),
                Ingredient("白糖", "1.5 勺"),
            ),
            description = "葱油拌面是上海人的灵魂 comfort food，炸得焦香的葱油裹住每根面条，咸甜交织。",
            article = Article(
                title = "一勺葱油的修行",
                author = "味道日历编辑部",
                sections = listOf(
                    ArticleSection("慢火炸葱", "小葱切段，冷油下锅小火慢炸，至葱叶焦黄酥脆，香气最浓时离火。"),
                    ArticleSection("酱油激香", "趁葱油还热，倒入生抽老抽白糖，余温会把酱汁激出复合香气。"),
                ),
            ),
            videos = listOf(
                VideoAsset("v1", "葱油拌面完整教学", SAMPLE_VIDEO, foodImage("葱油拌面"), 240),
            ),
            steps = listOf(
                CookingStep(1, "炸葱油", "小葱切段，冷油下锅小火慢炸至焦黄酥脆，捞出葱段。", 600, foodImage("炸葱油"), SAMPLE_VIDEO),
                CookingStep(2, "调葱油酱", "葱油中加生抽、老抽、白糖小火煮至糖化。", 120, foodImage("葱油酱"), null),
                CookingStep(3, "煮面", "面条煮至刚断生，捞出过一下温水沥干。", 240, foodImage("煮面"), null),
                CookingStep(4, "拌面", "面条倒入碗中，淋葱油酱翻拌均匀，撒焦葱段。", 60, foodImage("葱油拌面"), null),
            ),
        ),
        Dish(
            id = "pork_belly_potato",
            name = "五花肉炒土豆片",
            tagline = "焦香下饭，土豆吸饱肉香",
            cuisine = "家常菜",
            coverImageUrl = foodImage("五花肉炒土豆片"),
            difficulty = Difficulty.EASY,
            durationMinutes = 25,
            calories = 420,
            ingredients = listOf(
                Ingredient("五花肉", "250 克"),
                Ingredient("土豆", "2 个（约 300 克）"),
                Ingredient("青红椒", "各 1 个"),
                Ingredient("蒜片", "15 克"),
                Ingredient("生抽", "2 勺"),
                Ingredient("老抽", "半勺"),
                Ingredient("盐", "适量"),
                Ingredient("食用油", "1 勺"),
            ),
            description = "五花肉煸出油脂，土豆片吸饱肉香，煎至微焦金黄，是最朴实的下饭菜。",
            article = Article(
                title = "让土豆片不粘连的窍门",
                author = "味道日历编辑部",
                sections = listOf(
                    ArticleSection("土豆要泡水", "切好的土豆片用清水泡去淀粉，沥干再下锅，煎炒才不粘不散。"),
                    ArticleSection("先煸肉出油", "五花肉小火慢慢煸出油脂，用猪油炒土豆片更香更润。"),
                ),
            ),
            videos = listOf(
                VideoAsset("v1", "五花肉炒土豆片教学", SAMPLE_VIDEO, foodImage("五花肉炒土豆片"), 300),
            ),
            steps = listOf(
                CookingStep(1, "备料", "五花肉切薄片，土豆切薄片泡水沥干，青红椒切块。", 180, foodImage("切土豆片"), null),
                CookingStep(2, "煸五花肉", "冷锅下五花肉小火煸至卷曲出油、边缘微焦。", 180, foodImage("煸五花肉"), SAMPLE_VIDEO),
                CookingStep(3, "炒土豆片", "下土豆片中火煎炒至两面微黄断生。", 240, foodImage("煎土豆片"), null),
                CookingStep(4, "调味出锅", "加生抽、老抽、蒜片、青红椒翻炒断生，调盐出锅。", 90, foodImage("五花肉炒土豆片"), null),
            ),
        ),
        Dish(
            id = "red_braised_fish",
            name = "红烧鱼块",
            tagline = "酱汁浓稠，鱼肉鲜嫩入味",
            cuisine = "家常菜",
            coverImageUrl = foodImage("红烧鱼块"),
            difficulty = Difficulty.MEDIUM,
            durationMinutes = 35,
            calories = 320,
            ingredients = listOf(
                Ingredient("草鱼中段", "600 克"),
                Ingredient("姜片", "20 克"),
                Ingredient("葱段", "30 克"),
                Ingredient("蒜末", "10 克"),
                Ingredient("生抽", "2 勺"),
                Ingredient("老抽", "1 勺"),
                Ingredient("料酒", "2 勺"),
                Ingredient("白糖", "1 勺"),
                Ingredient("香醋", "半勺"),
            ),
            description = "红烧鱼块酱色红亮、鱼肉细嫩，关键是煎鱼不破皮、炖煮入味收汁浓稠。",
            article = Article(
                title = "煎鱼不破皮的两个要点",
                author = "味道日历编辑部",
                sections = listOf(
                    ArticleSection("热锅凉油", "锅烧到冒青烟再倒油，鱼块擦干水分下锅，中火煎至定型再翻面。"),
                    ArticleSection("醋去腥", "烹入少许香醋随蒸汽带走腥味，是红烧鱼块不腥的关键。"),
                ),
            ),
            videos = listOf(
                VideoAsset("v1", "红烧鱼块完整教学", SAMPLE_VIDEO, foodImage("红烧鱼块"), 420),
            ),
            steps = listOf(
                CookingStep(1, "处理鱼块", "草鱼中段切块，加盐、料酒腌制 10 分钟，擦干水分。", 600, foodImage("鱼块腌制"), null),
                CookingStep(2, "煎鱼块", "热锅凉油下鱼块，中火煎至两面金黄定型。", 360, foodImage("煎鱼块"), SAMPLE_VIDEO),
                CookingStep(3, "炝锅调味", "下姜片、葱段、蒜末爆香，烹料酒、香醋，加生抽、老抽、白糖。", 90, foodImage("炝锅调味"), null),
                CookingStep(4, "炖煮收汁", "加开水没过鱼块一半，中火炖 8 分钟，大火收汁浓稠。", 540, foodImage("红烧鱼块"), null),
            ),
        ),
        Dish(
            id = "tomato_meatball_soup",
            name = "番茄汽水丸子汤",
            tagline = "酸甜开胃，丸子Q弹多汁",
            cuisine = "家常菜",
            coverImageUrl = foodImage("番茄汽水丸子汤"),
            difficulty = Difficulty.MEDIUM,
            durationMinutes = 30,
            calories = 290,
            ingredients = listOf(
                Ingredient("猪肉末", "250 克"),
                Ingredient("番茄", "3 个"),
                Ingredient("蛋清", "1 个"),
                Ingredient("淀粉", "1 勺"),
                Ingredient("姜葱水", "3 勺"),
                Ingredient("盐", "适量"),
                Ingredient("白糖", "1 勺"),
                Ingredient("香醋", "少许"),
            ),
            description = "番茄煮出酸甜汤汁，手打肉丸滑嫩Q弹，加一勺汽水让汤底更清爽蓬松，开胃解腻。",
            article = Article(
                title = "丸子Q弹的秘密",
                author = "味道日历编辑部",
                sections = listOf(
                    ArticleSection("顺方向搅打上劲", "肉末加姜葱水、蛋清、淀粉顺一个方向搅打至上劲发黏，丸子才Q弹不散。"),
                    ArticleSection("汽水点睛", "汤底淋入少许汽水，气泡让丸子更蓬松，也带出一丝清新酸甜。"),
                ),
            ),
            videos = listOf(
                VideoAsset("v1", "番茄丸子汤教学", SAMPLE_VIDEO, foodImage("番茄汽水丸子汤"), 360),
            ),
            steps = listOf(
                CookingStep(1, "调肉馅", "肉末加姜葱水、蛋清、淀粉、盐顺方向搅打上劲。", 300, foodImage("调肉馅"), null),
                CookingStep(2, "炒番茄汤底", "番茄去皮切块，小火煸炒出红油汤汁，加开水煮沸。", 240, foodImage("炒番茄汤底"), SAMPLE_VIDEO),
                CookingStep(3, "下丸子", "转小火，用勺挖肉丸入汤，定型后不搅动。", 300, foodImage("下丸子"), null),
                CookingStep(4, "调味出锅", "加盐、白糖调味，淋少许香醋和汽水，撒葱花出锅。", 60, foodImage("番茄汽水丸子汤"), null),
            ),
        ),
        Dish(
            id = "hand_torn_cabbage",
            name = "手撕包菜",
            tagline = "脆爽开胃，三分钟出锅",
            cuisine = "湘菜",
            coverImageUrl = foodImage("手撕包菜"),
            difficulty = Difficulty.EASY,
            durationMinutes = 10,
            calories = 180,
            ingredients = listOf(
                Ingredient("包菜", "1 个（约 500 克）"),
                Ingredient("干辣椒", "5 个"),
                Ingredient("蒜末", "15 克"),
                Ingredient("五花肉", "50 克"),
                Ingredient("生抽", "1 勺"),
                Ingredient("香醋", "1 勺"),
                Ingredient("盐", "适量"),
            ),
            description = "手撕的包菜断面不规则更入味，旺火爆炒断生即出锅，脆爽酸辣最下饭。",
            article = Article(
                title = "为什么手撕比刀切好吃",
                author = "味道日历编辑部",
                sections = listOf(
                    ArticleSection("手撕更入味", "手撕断面参差不齐，比刀切更易吸附调料，口感也更脆。"),
                    ArticleSection("旺火快炒", "全程大火，包菜下锅不超过两分钟，断生即出锅才能保持脆爽。"),
                ),
            ),
            videos = listOf(
                VideoAsset("v1", "手撕包菜教学", SAMPLE_VIDEO, foodImage("手撕包菜"), 180),
            ),
            steps = listOf(
                CookingStep(1, "手撕包菜", "包菜去硬芯，用手撕成大片，洗净沥干水分。", 120, foodImage("手撕包菜"), null),
                CookingStep(2, "煸肉出油", "五花肉切片小火煸出油，下干辣椒、蒜末爆香。", 60, foodImage("煸肉爆香"), SAMPLE_VIDEO),
                CookingStep(3, "旺火爆炒", "大火下包菜快速翻炒，沿锅边淋生抽、香醋。", 90, foodImage("爆炒包菜"), null),
                CookingStep(4, "出锅", "加盐调味，翻匀断生立即出锅。", 30, foodImage("手撕包菜"), null),
            ),
        ),
        Dish(
            id = "chestnut_chicken",
            name = "板栗烧鸡",
            tagline = "板栗粉糯，鸡肉鲜香",
            cuisine = "家常菜",
            coverImageUrl = foodImage("板栗烧鸡"),
            difficulty = Difficulty.MEDIUM,
            durationMinutes = 45,
            calories = 480,
            ingredients = listOf(
                Ingredient("鸡腿肉", "500 克"),
                Ingredient("去壳板栗", "200 克"),
                Ingredient("姜片", "20 克"),
                Ingredient("葱段", "30 克"),
                Ingredient("生抽", "2 勺"),
                Ingredient("老抽", "1 勺"),
                Ingredient("料酒", "2 勺"),
                Ingredient("冰糖", "15 克"),
                Ingredient("八角", "1 颗"),
            ),
            description = "板栗烧鸡是秋冬经典，板栗吸饱鸡汤粉糯香甜，鸡肉酱香浓郁，一锅端最满足。",
            article = Article(
                title = "板栗不碎的技巧",
                author = "味道日历编辑部",
                sections = listOf(
                    ArticleSection("板栗晚下锅", "鸡肉先炖 15 分钟入味，再下板栗同炖，避免板栗久煮碎烂。"),
                    ArticleSection("过油更香", "板栗先过油炸至微黄，外层定型内里粉糯，炖煮不易散。"),
                ),
            ),
            videos = listOf(
                VideoAsset("v1", "板栗烧鸡完整教学", SAMPLE_VIDEO, foodImage("板栗烧鸡"), 540),
            ),
            steps = listOf(
                CookingStep(1, "备料", "鸡腿剁块，板栗去壳去皮，姜切片，葱切段。", 300, foodImage("备料"), null),
                CookingStep(2, "煎板栗", "板栗过油中火煎至表面微黄捞出。", 180, foodImage("煎板栗"), SAMPLE_VIDEO),
                CookingStep(3, "炒鸡块", "鸡块下锅煸炒至变色，加姜片、葱段、八角、冰糖炒上色。", 240, foodImage("炒鸡块"), null),
                CookingStep(4, "炖煮", "加生抽、老抽、料酒、热水没过鸡块，小火炖 15 分钟。", 900, foodImage("炖煮"), null),
                CookingStep(5, "下板栗收汁", "下板栗同炖 10 分钟，大火收汁浓稠出锅。", 600, foodImage("板栗烧鸡"), null),
            ),
        ),
        Dish(
            id = "sweet_sour_ribs",
            name = "糖醋排骨",
            tagline = "酸甜适口，色泽红亮",
            cuisine = "家常菜",
            coverImageUrl = foodImage("糖醋排骨"),
            difficulty = Difficulty.MEDIUM,
            durationMinutes = 50,
            calories = 520,
            ingredients = listOf(
                Ingredient("小排", "500 克"),
                Ingredient("生抽", "2 勺"),
                Ingredient("香醋", "3 勺"),
                Ingredient("白糖", "3 勺"),
                Ingredient("料酒", "2 勺"),
                Ingredient("姜片", "15 克"),
                Ingredient("葱段", "20 克"),
                Ingredient("白芝麻", "少许"),
            ),
            description = "糖醋排骨讲究糖醋比例黄金 1:1，排骨外焦里嫩，酱汁裹匀红亮挂霜，酸甜开胃。",
            article = Article(
                title = "黄金糖醋比例",
                author = "味道日历编辑部",
                sections = listOf(
                    ArticleSection("1:1:1 口诀", "生抽、香醋、白糖各一勺为一份，按排骨量等比放大，是糖醋味零失败的口诀。"),
                    ArticleSection("收汁要翻动", "大火收汁时不断翻动排骨，让酱汁均匀挂上，出锅前撒芝麻增香。"),
                ),
            ),
            videos = listOf(
                VideoAsset("v1", "糖醋排骨完整教学", SAMPLE_VIDEO, foodImage("糖醋排骨"), 600),
            ),
            steps = listOf(
                CookingStep(1, "焯水", "小排冷水下锅加料酒姜片煮开撇沫，捞出洗净。", 300, foodImage("焯水"), null),
                CookingStep(2, "炖排骨", "排骨加水、姜片、葱段小火炖 30 分钟至软烂，捞出沥干。", 1800, foodImage("炖排骨"), null),
                CookingStep(3, "煎排骨", "少许油下排骨中火煎至两面微焦。", 240, foodImage("煎排骨"), SAMPLE_VIDEO),
                CookingStep(4, "调糖醋汁", "生抽、香醋、白糖按 1:1:1 调成碗芡倒入锅中。", 60, foodImage("糖醋汁"), null),
                CookingStep(5, "收汁出锅", "中火收汁至浓稠挂匀，撒白芝麻出锅。", 180, foodImage("糖醋排骨"), null),
            ),
        ),
        Dish(
            id = "mala_xiangguo",
            name = "麻辣香锅",
            tagline = "一锅烩万物，麻辣过瘾",
            cuisine = "川菜",
            coverImageUrl = foodImage("麻辣香锅"),
            difficulty = Difficulty.MEDIUM,
            durationMinutes = 40,
            calories = 560,
            ingredients = listOf(
                Ingredient("虾", "200 克"),
                Ingredient("藕片", "150 克"),
                Ingredient("土豆片", "150 克"),
                Ingredient("午餐肉", "150 克"),
                Ingredient("花菜", "150 克"),
                Ingredient("火锅底料", "50 克"),
                Ingredient("干辣椒", "15 克"),
                Ingredient("花椒", "5 克"),
                Ingredient("蒜末", "20 克"),
                Ingredient("白芝麻", "少许"),
            ),
            description = "麻辣香锅把各种食材一锅烩炒，火锅底料打底，麻辣鲜香，荤素自搭配最过瘾。",
            article = Article(
                title = "香锅不水塌的要点",
                author = "味道日历编辑部",
                sections = listOf(
                    ArticleSection("食材先焯熟", "根茎类食材先焯水至八成熟，下锅只需裹味，避免出水让香锅变汤锅。"),
                    ArticleSection("底料要炒香", "火锅底料小火炒出红油再下食材，香味才能均匀裹住每一块。"),
                ),
            ),
            videos = listOf(
                VideoAsset("v1", "麻辣香锅完整教学", SAMPLE_VIDEO, foodImage("麻辣香锅"), 480),
            ),
            steps = listOf(
                CookingStep(1, "备料焯水", "藕片、土豆片、花菜焯水至八成熟捞出沥干。", 360, foodImage("焯水食材"), null),
                CookingStep(2, "炒底料", "小火下火锅底料、干辣椒、花椒炒出红油香气。", 120, foodImage("炒底料"), SAMPLE_VIDEO),
                CookingStep(3, "炒虾午餐肉", "下虾和午餐肉翻炒至虾变红。", 180, foodImage("炒虾"), null),
                CookingStep(4, "烩炒全部食材", "下所有焯好的蔬菜大火翻炒，让底料裹匀。", 180, foodImage("烩炒"), null),
                CookingStep(5, "出锅", "加蒜末、白芝麻翻匀出锅。", 60, foodImage("麻辣香锅"), null),
            ),
        ),
        Dish(
            id = "meicai_kourou",
            name = "梅菜扣肉",
            tagline = "肉烂味浓，梅菜吸油增香",
            cuisine = "客家菜",
            coverImageUrl = foodImage("梅菜扣肉"),
            difficulty = Difficulty.HARD,
            durationMinutes = 120,
            calories = 680,
            ingredients = listOf(
                Ingredient("带皮五花肉", "600 克"),
                Ingredient("梅干菜", "100 克"),
                Ingredient("生抽", "3 勺"),
                Ingredient("老抽", "2 勺"),
                Ingredient("蚝油", "1 勺"),
                Ingredient("冰糖", "20 克"),
                Ingredient("料酒", "2 勺"),
                Ingredient("姜片", "20 克"),
            ),
            description = "梅菜扣肉是客家名菜，五花肉蒸至入口即化，梅菜吸饱肉油咸香回甘，肥而不腻。",
            article = Article(
                title = "扣肉皮起虎纹的秘诀",
                author = "味道日历编辑部",
                sections = listOf(
                    ArticleSection("炸皮起虎纹", "五花肉煮后扎孔涂老抽，下油锅炸至肉皮起泡虎纹，蒸出来才软糯好看。"),
                    ArticleSection("梅菜要洗透", "梅干菜反复清洗去沙，加糖油炒香再垫底，蒸制时油香渗入才好吃。"),
                ),
            ),
            videos = listOf(
                VideoAsset("v1", "梅菜扣肉完整教学", SAMPLE_VIDEO, foodImage("梅菜扣肉"), 1200),
            ),
            steps = listOf(
                CookingStep(1, "煮肉", "五花肉冷水下锅加料酒姜片煮 20 分钟至筷子能插入。", 1200, foodImage("煮肉"), null),
                CookingStep(2, "炸皮", "肉皮扎孔涂老抽，下油锅炸至肉皮金黄起虎纹，泡冷水。", 360, foodImage("炸皮"), SAMPLE_VIDEO),
                CookingStep(3, "切肉腌制", "切 0.8cm 厚片，加生抽、老抽、蚝油、冰糖拌匀腌 20 分钟。", 1200, foodImage("腌制肉片"), null),
                CookingStep(4, "炒梅菜", "梅干菜洗净切碎，加少许糖油炒香垫碗底。", 240, foodImage("炒梅菜"), null),
                CookingStep(5, "扣蒸", "肉片皮朝下码在梅菜上，大火蒸 90 分钟。", 5400, foodImage("扣蒸"), null),
                CookingStep(6, "翻扣出锅", "蒸好后倒扣出盘，浇原汁即可。", 60, foodImage("梅菜扣肉"), null),
            ),
        ),
        Dish(
            id = "wanzhou_grilled_fish",
            name = "万州烤鱼（草鱼）",
            tagline = "先烤后炖，麻辣鲜香一锅端",
            cuisine = "川菜",
            coverImageUrl = foodImage("万州烤鱼"),
            difficulty = Difficulty.HARD,
            durationMinutes = 70,
            calories = 580,
            ingredients = listOf(
                Ingredient("草鱼", "1 条（约 1000 克）"),
                Ingredient("藕片", "200 克"),
                Ingredient("豆皮", "150 克"),
                Ingredient("魔芋", "150 克"),
                Ingredient("郫县豆瓣酱", "2 勺"),
                Ingredient("干辣椒", "20 克"),
                Ingredient("花椒", "10 克"),
                Ingredient("蒜末", "20 克"),
                Ingredient("孜然粉", "1 勺"),
                Ingredient("料酒", "2 勺"),
            ),
            description = "万州烤鱼先腌后烤再炖，鱼皮焦香鱼肉嫩滑，配菜吸饱麻辣汤汁，一锅端最过瘾。",
            article = Article(
                title = "烤鱼不散的要点",
                author = "味道日历编辑部",
                sections = listOf(
                    ArticleSection("从背开鱼", "草鱼从背部剖开不切断腹部，展开成片更易烤透，翻面也不散。"),
                    ArticleSection("先烤后炖", "鱼先烤至皮焦七八成熟，再浇汤汁小火炖，外焦里嫩不碎。"),
                ),
            ),
            videos = listOf(
                VideoAsset("v1", "万州烤鱼完整教学", SAMPLE_VIDEO, foodImage("万州烤鱼"), 840),
            ),
            steps = listOf(
                CookingStep(1, "处理腌制", "草鱼从背剖开，加料酒、盐、孜然粉、姜片腌制 20 分钟。", 1200, foodImage("腌制草鱼"), null),
                CookingStep(2, "烤鱼", "鱼摊开刷油，入烤箱 220 度烤 20 分钟至皮焦。", 1200, foodImage("烤鱼"), SAMPLE_VIDEO),
                CookingStep(3, "炒底料配菜", "下豆瓣酱、干辣椒、花椒、蒜末炒红油，加藕片、豆皮、魔芋翻炒。", 240, foodImage("炒底料配菜"), null),
                CookingStep(4, "炖煮", "烤鱼放配菜上，加少许水小火炖 10 分钟入味。", 600, foodImage("炖煮烤鱼"), null),
                CookingStep(5, "出锅", "撒孜然粉、干辣椒段，浇热油激香出锅。", 60, foodImage("万州烤鱼"), null),
            ),
        ),
        Dish(
            id = "steamed_pork_potato",
            name = "粉蒸五花肉土豆",
            tagline = "米粉裹肉，土豆垫底吸香",
            cuisine = "家常菜",
            coverImageUrl = foodImage("粉蒸五花肉土豆"),
            difficulty = Difficulty.MEDIUM,
            durationMinutes = 60,
            calories = 460,
            ingredients = listOf(
                Ingredient("五花肉", "400 克"),
                Ingredient("土豆", "2 个"),
                Ingredient("蒸肉米粉", "150 克"),
                Ingredient("生抽", "2 勺"),
                Ingredient("老抽", "1 勺"),
                Ingredient("豆瓣酱", "1 勺"),
                Ingredient("料酒", "1 勺"),
                Ingredient("姜末", "10 克"),
            ),
            description = "粉蒸肉米粉裹住五花肉，蒸出油脂被土豆吸收，肉烂米香，土豆绵软入味。",
            article = Article(
                title = "蒸肉米粉的讲究",
                author = "味道日历编辑部",
                sections = listOf(
                    ArticleSection("米粉自制更香", "大米加八角花椒小火炒至微黄，打碎成粗颗粒，比买的更香更有嚼劲。"),
                    ArticleSection("土豆垫底", "土豆切块垫碗底，蒸制时吸收肉汁油脂，比肉还抢手。"),
                ),
            ),
            videos = listOf(
                VideoAsset("v1", "粉蒸五花肉教学", SAMPLE_VIDEO, foodImage("粉蒸五花肉土豆"), 720),
            ),
            steps = listOf(
                CookingStep(1, "腌制肉片", "五花肉切 0.5cm 片，加生抽、老抽、豆瓣酱、料酒、姜末腌 20 分钟。", 1200, foodImage("腌制肉片"), null),
                CookingStep(2, "裹米粉", "腌好的肉片裹满蒸肉米粉，加少许水拌匀让米粉湿润。", 180, foodImage("裹米粉"), SAMPLE_VIDEO),
                CookingStep(3, "码碗", "土豆切块垫碗底，肉片码在土豆上方。", 120, foodImage("码碗"), null),
                CookingStep(4, "上锅蒸", "大火蒸 40 分钟至肉烂土豆软。", 2400, foodImage("蒸制"), null),
                CookingStep(5, "出锅", "倒扣出盘，撒葱花即可。", 30, foodImage("粉蒸五花肉土豆"), null),
            ),
        ),
        Dish(
            id = "steamed_wuchang_fish",
            name = "清蒸武昌鱼",
            tagline = "原汁原味，鲜嫩清甜",
            cuisine = "鄂菜",
            coverImageUrl = foodImage("清蒸武昌鱼"),
            difficulty = Difficulty.EASY,
            durationMinutes = 20,
            calories = 240,
            ingredients = listOf(
                Ingredient("武昌鱼", "1 条（约 500 克）"),
                Ingredient("葱丝", "20 克"),
                Ingredient("姜丝", "20 克"),
                Ingredient("红椒丝", "10 克"),
                Ingredient("蒸鱼豉油", "3 勺"),
                Ingredient("料酒", "1 勺"),
                Ingredient("食用油", "2 勺"),
            ),
            description = "清蒸武昌鱼讲究火候精准，鱼刚断生即出锅，淋上热油激香葱丝，肉质细嫩清甜。",
            article = Article(
                title = "清蒸鱼的火候",
                author = "味道日历编辑部",
                sections = listOf(
                    ArticleSection("上汽再入锅", "蒸锅水烧开上汽后再放鱼，高温快速锁住鲜味，鱼肉不腥不老。"),
                    ArticleSection("热油激香", "出锅后铺葱丝姜丝，浇滚烫热油激出香气，再淋蒸鱼豉油。"),
                ),
            ),
            videos = listOf(
                VideoAsset("v1", "清蒸武昌鱼教学", SAMPLE_VIDEO, foodImage("清蒸武昌鱼"), 300),
            ),
            steps = listOf(
                CookingStep(1, "处理鱼", "武昌鱼去鳞去内脏洗净，两面划刀，抹料酒姜片去腥。", 300, foodImage("处理鱼"), null),
                CookingStep(2, "上锅蒸", "水烧上汽，鱼盘放蒸锅大火蒸 8 分钟。", 480, foodImage("蒸鱼"), SAMPLE_VIDEO),
                CookingStep(3, "铺葱丝", "倒掉盘中蒸汁，铺上葱丝、姜丝、红椒丝。", 60, foodImage("铺葱丝"), null),
                CookingStep(4, "浇油淋汁", "热油浇在葱丝上激香，淋蒸鱼豉油即可。", 60, foodImage("清蒸武昌鱼"), null),
            ),
        ),
        Dish(
            id = "stir_fried_okra",
            name = "清炒秋葵",
            tagline = "清爽脆嫩，三分钟上桌",
            cuisine = "家常菜",
            coverImageUrl = foodImage("清炒秋葵"),
            difficulty = Difficulty.EASY,
            durationMinutes = 10,
            calories = 120,
            ingredients = listOf(
                Ingredient("秋葵", "300 克"),
                Ingredient("蒜末", "15 克"),
                Ingredient("盐", "适量"),
                Ingredient("食用油", "1 勺"),
                Ingredient("生抽", "半勺"),
            ),
            description = "清炒秋葵翠绿脆嫩，保留黏液营养，蒜香清爽，是低卡健康的快手家常菜。",
            article = Article(
                title = "秋葵翠绿不发黑的窍门",
                author = "味道日历编辑部",
                sections = listOf(
                    ArticleSection("先焯水", "秋葵整根下沸水焯 30 秒捞出再切，可减少黏液流失，颜色更翠绿。"),
                    ArticleSection("整根焯再切", "先切后焯会让黏液和营养大量流失，整根焯好再切段最佳。"),
                ),
            ),
            videos = listOf(
                VideoAsset("v1", "清炒秋葵教学", SAMPLE_VIDEO, foodImage("清炒秋葵"), 180),
            ),
            steps = listOf(
                CookingStep(1, "焯水", "秋葵整根下沸水焯 30 秒捞出过凉，切斜段。", 60, foodImage("焯秋葵"), null),
                CookingStep(2, "炝锅", "热油下蒜末爆香。", 30, foodImage("炝锅"), SAMPLE_VIDEO),
                CookingStep(3, "快炒出锅", "下秋葵大火快炒 1 分钟，加盐、生抽翻匀出锅。", 60, foodImage("清炒秋葵"), null),
            ),
        ),
    )
}
